name: adr
description: Utility for maintaining consistent Architectural Design Records (ADRs) for Dart/Flutter projects.
version: 1.0.0
homepage: https://github.com/stelynx/dart-adr
repository: https://github.com/stelynx/dart-adr

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: 1.6.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

executables:
  adr: adr
